### ISSUE TITLE
Android: No permission when copying files.

### ISSUE THREAD

**Issue by wh201906** [jd1378/react-native-saf-x#2]
Hi.
On Android 11, when copying files, I got a error like this
```
Error: You don't have read/write permission to access uri: content://com.android.providers.media.documents/documet/documentXXXX
```
I have granted the file access permission to my app, but this error still occurs.
You can reproduce this bug on the Joplin pre-release v2.9.3 [cea1aea](https://github.com/laurent22/joplin/commit/cea1aeac4b0af498290e2bc8ca3030a6f6eb17c7)
The bug is also talked there. 
https://discourse.joplinapp.org/t/cannot-attaching-documents-not-images-in-v2-9-3-on-android/27709

**Comment by jd1378** [comment]
hmm,
I had not check for RNFS usages in other places
this probably is not happening during sync, but in other places which I have not checked when making the pr
I'll try to make a pr for the issue

**Comment by jd1378** [comment]
I'm closing this since it does not belong here and the pr im going to make is not related to this module
