### ISSUE TITLE
Task :react-native-saf-x:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by kd-fs** [jd1378/react-native-saf-x#4]
Hello,
When I test my application on AVD and on my cell phone, everything works. When I generate the Release APK I get the error : 
![Capture d’écran du 2023-01-17 13-46-20](https://user-images.githubusercontent.com/97320216/212902573-6740974d-9e8c-47ea-8a19-b7529a90a919.png)

**Comment by jd1378** [comment]
Hi
this is a known [issue](https://github.com/laurent22/joplin/pull/6395#issuecomment-1374917535),
I'm currently updating the module to be efficient as well (currently is super slow and blocks ui)
will be fixed in a few days ;)
(few days = 1-3 days, as I have rewritten the major parts)

**Comment by kd-fs** [comment]
Okay, courage

**Comment by jd1378** [comment]
Hi @kd-fs 
please try [v2.0.0](https://www.npmjs.com/package/react-native-saf-x)
I hope this fixes your issue :)

**Comment by jd1378** [comment]
I'm closing this issue, feel free to create another if issue persist
