### ISSUE TITLE
saving files other than text(image, zip etc.)

### ISSUE THREAD

**Issue by yuameshi** [jd1378/react-native-saf-x#5]
can i save an image downloaded from web by fetch?

i've tried this, bus obviously it failed. is the library desn't support saving file? if that, are there any better lib can handle this? or how i can resolve this problem.

```javascript
const file = await (await fetch(SOME_URL)).text() // it will be arrayBuffer() normally
writeFile(
safUri+'/123456.jpg',
file,
{
	//mimeType: 'application/octet-stream',
});
```

**Comment by jd1378** [comment]
I'm not sure
I probably have to check stuff

for now you can try using [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util), not sure if it does what you want though

**Comment by jd1378** [comment]
you can download your file using [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util) to your app's data folder, then use my module to move it where user has selected

**Comment by yuameshi** [comment]
i'll try for it tonight

**Comment by yuameshi** [comment]
i've followed your instructions, using RNBlobUtil to solve the question.

but maybe there're a small bug, when i set `replaceIfDestinationExists` to `true`, it throws exception, but it did moved the file, let me have try for copyFile

```
ERROR  [Error: Attempt to invoke virtual method 'android.os.Bundle android.content.ContentProviderClient.call(java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference]
```

```javascript
// ts code
await moveFile(response.path(), safUri + `/filename.jpg`, {replaceIfDestinationExists: true});
```

![IMG_20230407_144129.jpg](https://user-images.githubusercontent.com/64469437/230556284-dbd64dcb-61c8-4b1e-8121-b6b6c58cb442.jpg)

## ENV INFO 
```
# npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 4.4 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) arm64 unknown
    Memory: 765.51 MB / 3.63 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: Not Found
    npm: 9.6.2 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
  npmGlobalPackages:
    *react-native*: Not Found
```
because without dep changes we needn't build a new apk to develop, so i didn't install android sdk and java on this machine(i use another machine to build apk and i comfim the apk includes `rn-saf-x` & `rn-blob-util`)

**Comment by yuameshi** [comment]
solved by replacing `moveFile` with `copyFile`

**Comment by jd1378** [comment]
I'm glad you could work it out

btw if you think something should be improved feel free to send a PR :)
